language:
  - c
  - cpp
compiler:
  - gcc

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get install cmake git scons libssl-dev libpq-dev libossp-uuid-dev libjansson-dev libevent-dev
  - git clone https://github.com/netvirt/netvirt.git
  - cd netvirt
  - git submodule init
  - git submodule update
  - pushd udt4 && make && popd
  - pushd libconfig && touch lib/*.c && ./configure && make && popd
  - pushd tapcfg && ./buildall.sh || true && popd

script:
- 'mkdir build && cd build && cmake .. -DWITH_NVAGENT=no -DWITH_NVSWITCH=YES -DWITH_NVCTRLER=YES && make'
- 'tar -czvf netvirt.tar.gz *'
- 'curl -T netvirt.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/'
